# Copyright (c) 2016-2020 Martin Donath <martin.donath@squidfunk.com>

site_name: Uniformly-Damped Binomial Filter
repo_name: UniformlyDampedBinomialFilter
repo_url: https://github.com/somefunagba/uniformlydampedbinomialfilter
edit_uri: ''
site_author: Oluwasegun Somefun
site_description: >-
  On the uniformly damped binomial filter using tools from modern control theory, and signal processing.
  Available for use for your open-source project

copyright: Copyright &copy; 2019 - 2020. Oluwasegun Somefun
remote_branch: gh-pages
remote_name: origin
dev_addr: '127.0.0.1:8801'
docs_dir: 'docs'
site_dir: 'site'

# Page tree
nav:
  - Home: 'index.md'
  - Guide: 'guide.md'
#  - About:
#    - About: 'about/about.md'
#    - License: 'about/license.md'
#  - Releases:
#    - Release Log: 'releases/release.md'

# Theme Configuration
#theme:
#  name: material
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    #- instant
  palette:
    scheme: default #slate
    primary: deep blue
    accent: deep brown
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/function-variant  #fontawesome/brands/youtube
  favicon: assets/images/favicon.png



# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      linenums: true
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
        # - pymdownx.highlight:
      #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


  # Plugins
plugins:
  - search
  - minify:
      minify_html: false
  - git-revision-date-localized:
      type: date #datetime, timeago


extra_javascript:
  - javascripts/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

# Customizations

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/somefunagba
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/somefunagba
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/oluwasegunsomefun/